#!/bin/bash

set -e

NDK_PATH_TO_USE=/home/yckj1701/usr/android-ndk-r15c

if [ $# -gt 0 ] ; then
    NDK_PATH_TO_USE=$1
fi

cmake ../ \
-DCMAKE_TOOLCHAIN_FILE=$NDK_PATH_TO_USE/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_INSTALL_PREFIX=$(pwd)/install \
-DANDROID_ABI="armeabi-v7a" \
-DANDROID_STL=gnustl_static \
-DANDROID_NATIVE_API_LEVEL=android-21 \
-DMNN_BUILD_FOR_ANDROID_COMMAND=ON \
-DMNN_USE_LOGCAT=OFF \
-DMNN_BUILD_BENCHMARK=OFF \
-DMNN_USE_SSE=OFF \
-DMNN_SUPPORT_BF16=OFF \
-DMNN_BUILD_TEST=ON \
-DMNN_BUILD_HARD=OFF \
-DMNN_BUILD_SHARED_LIBS=OFF \
-DMNN_FORBID_MULTI_THREAD=OFF \
-DMNN_OPENMP=OFF \
-DMNN_USE_THREAD_POOL=ON \
-DMNN_BUILD_TRAIN=OFF \
-DMNN_BUILD_DEMO=OFF \
-DMNN_BUILD_QUANTOOLS=OFF \
-DMNN_EVALUATION=OFF \
-DMNN_BUILD_CONVERTER=OFF \
-DMNN_SUPPORT_TFLITE_QUAN=ON \
-DMNN_DEBUG_MEMORY=OFF \
-DMNN_DEBUG_TENSOR_SIZE=OFF \
-DMNN_BUILD_TOOLS=ON \
-DMNN_GPU_TRACE=OFF \
-DMNN_PORTABLE_BUILD=OFF \
-DMNN_SEP_BUILD=OFF \
-DMNN_AAPL_FMWK=OFF \
-DMNN_METAL=OFF \
-DMNN_OPENCL=ON \
-DMNN_OPENGL=OFF \
-DMNN_VULKAN=OFF \
-DMNN_ARM82=OFF \
-DMNN_USE_CPP11=ON