#!/bin/bash

set -e

cmake .. \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=./install \
	-DMNN_SEP_BUILD=OFF \
	-DMNN_BUILD_SHARED_LIBS=ON \
	-DMNN_BUILD_DEMO=ON \
	-DMNN_BUILD_TEST=ON \
	-DMNN_BUILD_BENCHMARK=ON \
	-DMNN_BUILD_TOOLS=ON \
	-DMNN_BUILD_QUANTOOLS=ON \
	-DMNN_EVALUATION=ON \
	-DMNN_BUILD_CONVERTER=ON \
	-DMNN_PORTABLE_BUILD=ON \
	-DMNN_AVX512=OFF \
	-DMNN_OPENCL=ON\
	-DMNN_VULKAN=ON